name: 'Get Algolia Issue Records'
description: 'Get a number of related Issues from Algolia Bot Index'

branding:
  icon: 'search'  
  color: 'blue'

inputs:
  app_id:
    description: 'ID of this application in your Algolia account'
    required: true
  api_key:
    description: 'API key with search permissions to the index in your Algolia account'
    required: true
  index_name:
    description: 'Name of the index to search this record'
    required: true
  issue_title: 
    description: 'Title from the Issue to base search on'
    required: true
  max_results:
    description: 'The maximum number of search results to return'
    required: false
    default: 3
outputs:
  comment_body:
    description: 'A comment body that contains a default headline and some number of related issues as markdown'
  issues_list:
    description: 'Markdown representation of the results returned by Algolia. Output as a MD list'
runs:
  using: 'node12'
  main: 'dist/index.js'

